### ISSUE TITLE
Shared folder under Windows doesn't get updated with sources

### ISSUE THREAD

**Issue by JBusch** [Tuurlijk/TYPO3.Homestead#20]
Hey,

the shared folder under windows works, but no sources are getting deployed an no typo3 websites are being generated, the folder just stays empty.

beside your configuration, i also tried smb and nfs(with the winnfs plugin https://github.com/winnfsd/vagrant-winnfsd) with the same results.

**Comment by TomOne** [comment]
I can confirm this issue.

**Comment by TomOne** [comment]
Perhaps this isn’t a Windows-only issue.

I tried to set up the synced folder with a Linux host (using the rsync method, because NFS didn’t work for some reason) and got the same results: an empty `/var/www/` folder on the VM.

Is there a debug log on the VM from which we can understand what’s going on?

**Comment by TomOne** [comment]
This is a known problem with Vagrant. See http://stackoverflow.com/questions/19231895/how-to-share-a-folder-created-inside-vagrant, mitchellh/vagrant#936.

Apparently there’s no other way than implementing some kind of workaround for this.
