### ISSUE TITLE
Version 6.2 doesnt work correctly..

### ISSUE THREAD

**Issue by mpathy** [Tuurlijk/TYPO3.Homestead#28]
The version that is found at: 
http://6.2.local.typo3.org/typo3/
http://6.2.local.typo3.org/
..doesnt work.

This is the error message:

> Fatal error: Uncaught TypeError: Argument 1 passed to TYPO3\CMS\Core\Error\AbstractExceptionHandler::handleException() must be an instance of Exception, instance of TypeError given in /var/www/6.2.local.typo3.org/typo3_src/typo3/sysext/core/Classes/Error/AbstractExceptionHandler.php:38 Stack trace: #0 [internal function]: TYPO3\CMS\Core\Error\AbstractExceptionHandler->handleException(Object(TypeError)) #1 {main} thrown in /var/www/6.2.local.typo3.org/typo3_src/typo3/sysext/core/Classes/Error/AbstractExceptionHandler.php on line 38

Otherwise, great job, this box is very useful for testing!

**Comment by Tuurlijk** [comment]
Hi,

This is a known issue. I think the front page is broken, but the other pages of the site work. The box runs PHP 7 by default which is not good for TYPO3 6.2.

I may make a separate configuration for TYPO3 6.2 in nginx so that is can use a PHP 5.6 backend instead of the default 7. That will prevent the errors.

**Comment by mpathy** [comment]
Ah of course.. Yes, that must be the reason.. 
PHP7 and Typo3 6.x doesnt work so well..
But I can use the the PHP override URL now, thx.
